### ISSUE TITLE
dataset error

### ISSUE THREAD

**Issue by wossg-999** [ahmadmughees/SH17dataset#3]
Very good work, hello, I am experiencing the following reported error when using your dataset, is there a problem with your ,txt file?

 File "/root/miniconda3/lib/python3.8/pathlib.py", line 872, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: PosixPath('.') has an empty name

**Comment by ahmadmughees** [comment]
Hi @wossg-999 

Thanks for reaching out. 

The text file with the dataset contains only list of images while in the yolo format it need full image path, so append the full path within each file `train_files.txt` and `val_files.txt`. Your files should have the structure as below. 
  
```
\full\path\to\images\pexels-photo-11739107.jpeg
\full\path\to\images\pexels-photo-6766248.jpeg
\full\path\to\images\pexels-photo-7674606.jpeg
\full\path\to\images\pexels-photo-7222236.jpeg
\full\path\to\images\pexels-photo-8837596.jpeg
```

let me know if this solves your issue and if you need any more help.

**Comment by wossg-999** [comment]
Excellent! Thank you for your patient answer.

**Comment by ahmadmughees** [comment]
Perfect! I'm closing the issue.

**Comment by ahmadmughees** [comment]
Hi @wossg-999! 

I just wrote a small script to update `train_files.txt` and `test_files.txt` for others as well and added a note in readme as well. Thanks. 

```
import os


def update(file_path: str, root: str):
    with open(file_path, "r") as file:
        paths = file.readlines()

    updated_paths = list[str]()
    for path in paths:
        path = path.strip()
        updated_paths.append(root + path + "\n")

    new_file_name = "updated_" + os.path.basename(file_path)
    new_file_path = os.path.join(os.path.dirname(file_path), new_file_name)

    with open(new_file_path, "w") as file:
        file.writelines(updated_paths)

    print("Updated file created successfully: " + new_file_path)


def main():
    root = "/your/path/to/dataset/directory"
    update(file_path=r"/full/path/to/train_files.txt", root=root)
    update(file_path=r"/full/path/to/test_files.txt", root=root)


if __name__ == "__main__":
    main()

```

**Comment by wossg-999** [comment]
Hi @ahmadmughees, 

Thank you for your prompt response and for providing the script update. I appreciate your efforts in adding a note to the README file and including the updated train_files.txt and test_files.txt.

I'll review the changes and test the new script on my end. If I encounter any further issues or have additional questions, I'll reach out.

Thanks again for your support!
